worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    resolver 127.0.0.11 valid=2s;

    server {
        listen 80;
        server_name localhost;

        location /api/v1/orders {
            set $orders_backend http://orders_service:8002;
            proxy_pass $orders_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Connection "";
        }

        location /api/v1/guitars {
            set $products_backend http://products_service:8000;
            proxy_pass $products_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Connection "";
        }

        location /api/v1/auth {
            set $auth_backend http://auth_service:8000;
            proxy_pass $auth_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Connection "";
        }
    }
}