# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobufs/product.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protobufs/product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protobufs/product.proto\x12\x08products\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"\x8a\x02\n\x12GetProductResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0b\n\x03sku\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\r\n\x05\x62rand\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x01\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x11\n\tbody_wood\x18\x08 \x01(\t\x12\x11\n\tneck_wood\x18\t \x01(\t\x12\x16\n\x0e\x66retboard_wood\x18\n \x01(\t\x12\x12\n\nfret_count\x18\x0b \x01(\x05\x12\x14\n\x0cscale_length\x18\x0c \x01(\x01\x12\x15\n\rpickup_config\x18\r \x01(\t\x12\x11\n\timage_url\x18\x0e \x01(\t2Y\n\x0eProductService\x12G\n\nGetProduct\x12\x1b.products.GetProductRequest\x1a\x1c.products.GetProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTREQUEST']._serialized_start=37
  _globals['_GETPRODUCTREQUEST']._serialized_end=76
  _globals['_GETPRODUCTRESPONSE']._serialized_start=79
  _globals['_GETPRODUCTRESPONSE']._serialized_end=345
  _globals['_PRODUCTSERVICE']._serialized_start=347
  _globals['_PRODUCTSERVICE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
